Ke/test report (#19)
* add junit

* use test reporter

* test broken unit test ui

* test report only

* publish unit test

* always run unit test result

* push to default branch

* test branches **

* only trigger workflow  on release branch

* test report only

* test report

* only generate summary

* make ng test pass

* try using digit regex branch name pattern

* update version

* remove comment from github action

* update regex

* update regex

* update regex

* update name to JEST test result

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,7 +23,7 @@ on:
 env:
   MAJOR_VERSION: 3
   MINOR_VERSION: 0
-  PATCH_VERSION: 0
+  PATCH_VERSION: 1
   publishProduction: 'false'
   publishPreview: 'false'
 
@@ -58,6 +58,15 @@ jobs:
   
       - name: Npm run test
         run: npm run test:ci
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Jest Test Results
+          path: ./*.xml
+          reporter: jest-junit
+          only-summary: 'true'
 
       - name: Npm run build
         run: npm run build
