Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,6 +22,8 @@ jobs:
       NPM_USERNAME: dummy
       NPM_EMAIL: dummy
       NPM_REGISTRY: dummy
+    permissions:
+     checks: write # required by test-reporter https://github.com/dorny/test-reporter/issues/149
 
     steps:
       - uses: actions/checkout@v2
@@ -46,8 +48,18 @@ jobs:
         run: npm run lint
 
       - name: Npm run test
-        run: npm run test:ci
-
+        run: npm run test:ci\
+        
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Jest Test Results
+          path: ./*.xml
+          reporter: jest-junit
+          only-summary: 'true'
+          fail-on-error: 'false'
+          
       - name: Npm run build
         run: npm run build
 
